services:
  web:
    build: .
    image: web:latest
    volumes:
      - static:/app/.static
    command: gunicorn
    depends_on:
      - db
    environment:
      - ALLOWED_HOSTS=localhost
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
    restart: always

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db:/var/lib/postgresql/data

  nginx:
    build: ./.docker/nginx
    image: nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static:/www/static/

volumes:
  db:
  static:
