[tool.ruff]
extend-exclude = [
    ".github",
    ".idea",
    ".local",
    ".static",
    "__pycache__",
    "migrations",
    "manage.py",
    "tests.py",
]
line-length = 120
target-version = "py312"
